### ISSUE TITLE
Address validation

### ISSUE THREAD

**Issue by fanatid** [ethereumjs/ethrpc#32]
Address validation use regexp `^0x[0-9a-fA-F]*$` https://github.com/ethereumjs/ethrpc/blob/4f3789895d5ad7830befe629f7bb304afb28ecd0/src/validate/validate-address.js#L14
not sure, but should not you check checksum if address has upper case symbols?

**Comment by MicahZoltu** [comment]
I believe better address validation could be done.  What is in there now is a pretty naive sanity check.  If you happen to have a link to a better mechanism for address validation feel free to drop a link.  :)

**Comment by fanatid** [comment]
@MicahZoltu this should work:
```js
"use strict";
var sha3 = require("../utils/sha3");

function checksumAddress (address) {
  address = address.slice(2).toLowerCase();
  var hash = sha3(address, "hex");
  var ret = "0x";

  for (var i = 0; i < address.length; i++) {
    if (parseInt(hash[i], 16) >= 8) {
      ret += address[i].toUpperCase();
    } else {
      ret += address[i];
    }
  }

  return ret;
}

var validateAddress = function (address) {
  if (address === null || address === undefined) {
    throw new Error("address is required");
  }
  if (typeof address !== "string") {
    throw new Error("address must be a string but was " + typeof address);
  }
  if (address.slice(0, 2) !== "0x") {
    address = "0x" + address;
  }
  if (address.length !== 42) {
    throw new Error("address must be 42 characters, 20 bytes (2 hex encoded code points each) plus the 0x prefix.  Length: " + address.length);
  }
  if (!/^0x[0-9a-fA-F]{40}$/.test(address)) {
    throw new Error("address can only contain 0-9 and a-F and must start with 0x.  Provided: " + address);
  }
  if (/[a-f]+/.test(address) && /[A-F]+/.test(address) && checksumAddress(address) !== address) {
    throw new Error("address checksum is invalid.");
  }
  return address;
};

module.exports = validateAddress;
```

**Comment by MicahZoltu** [comment]
@fanatid I'm guessing at this point you don't really care anymore, but I just noticed this issue was never implemented.  A PR is welcome.   Same to anyone else interested in this, a PR that improves the validation would be welcome (should be as simple as just dropping the above code into a file and hooking it up).

**Comment by MicahZoltu** [comment]
Fixed by #42

**Comment by kiter32** [comment]
Address "undefined" is invalid. - Address must be a hex value of 20 bytes (40 hex characters). - Address must match its checksum counterpart. - I have this problem, Mint doesn’t work on the site, what should I do? what should I fix?

**Comment by acolytec3** [comment]
This is an unmaintained repo at this point and it's not clear how this question relates. Will close.
