### ISSUE TITLE
Resubmit unfulfilled transactions to eth node after a predetermined timeout

### ISSUE THREAD

**Issue by justinbarry** [ethereumjs/ethrpc#72]

**Comment by MicahZoltu** [comment]
This is necessary to avoid transactions getting silently dropped and having the request stay in memory forever.  Also, silently dropping data is bad for the app.

**Comment by pgebheim** [comment]
What's the idea here?

**Comment by adrake33** [comment]
CH ticket created here: https://app.clubhouse.io/augur/story/17759/websocket-transport-will-not-submit-timed-out-requests. Talked to Justin about this, but he wasn't sure where the exact code was that was causing the problem.
